database.sqlite.name: rynocheck.db

# [Name, CODE, micro-transaction max value]
currency.default.entity: [AncapCoin, ANC, 100]

# from 0 to 1
currency.default.fee.value: 0.01

# account name
currency.default.fee.recipient: henryco

# minimum 1
transaction.pool.size: 5
transaction.self: true
