database.sqlite.name: rynocheck.db

# [Name, CODE, micro-transaction max value]
currency.default: [AncapCoin, ANC, 100]

# from 0 to 1
transaction.fee.value: 0.01

# account name
transaction.fee.recipient: henryco

# minimum 1
transaction.pool.size: 10
