name: RynoCheck
version: 1.4.8.8
description: Free market intensifies

author: HenryCo
website: https://github.com/henryco
main: net.henryco.rynocheck.RynoCheckPlugin

commands:
    nap:
      description: You should agree with NAP contract
      usage: /<command> [on / off]

    y:
      description: Confirm action
      usage: /<command>
      aliases: [yes, accept, ok, Y]

    n:
      description: Decline action
      usage: </command>
      aliases: [no, decline, cancel, N]

    wallet-login:
      description: Login to your personal wallet
      usage: /<command> {name} {password}
      aliases: [wln, wlogin, w-login]
      permissions: wallet_logout
      permissions-message: You should logout first

    wallet-logout:
      description: Logout
      usage: </command>
      aliases: [wlt, wlogout, w-logout]
      permissions: wallet_login
      permissions-message: You should login first

    wallet-create:
      description: Create new wallet account
      usage: /<command> {name} {password} {(optional) email}
      aliases: [wcr, wcreate, w-create]

    wallet:
      description: Your personal money wallet
      aliases: [w]
      usage: |
        /<command> [send {recipient} {amount} {currency}],
        [balance], [balance {currency}],
        [history], [history {currency}]
      permission: wallet_login
      permission-message: You should login to personal wallet first.




permissions:
    nap_member.*:
      description: NAP member
      children:
        nap_member.revenge: true
        nap_member.private_property: true
    nap_member.revenge:
      description: J U S T I C E for all
      default: true
    nap_member.private_property:
      description: You deserve it!
      default: true
    wallet_login:
      description: Wallet login
      default: false
    wallet_logout:
      description: Wallet logout
      default: true